name: package-testing
channels:
  - defaults
dependencies:
  - python >=3.9,<3.10
  # dev/test
  - pytest
  - pytest-cov
  - pytest-html
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pillow
  - scikit-learn
  - conda-build
  - anaconda-client
  - pip:
      - allure-pytest==2.9.45
