name: Integration Tests Daily Run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  cd:
    name: Daily Cron Job
    runs-on: self-hosted-eks
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup Environment
        run: |
          source $CONDA/etc/profile.d/conda.sh
          make environment
      - name: CronJob
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate package-testing
          make test
      - name: Upload Run Artifacts
        if: always()
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: run-artifacts
          path: artifacts/**
          retention-days: 20
