name: "Add repo"
on:
  workflow_dispatch:
    inputs:
      feedstocks:
        description: 'Feedstocks that will be added. To add multiple at once separate by comma'
        required: true
        type: string
permissions: write-all

jobs:
  add-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        run: |
          for repo in ${REPO_LIST//,/ }; do 
            echo "Checking input $repo"
            if [[ ! $repo =~ ^[A-Za-z0-9_.-]+-feedstock$ ]]; then
                echo "Invalid input $repo. Please enter in of the form <library>-feedstock"
                exit 1
            fi
          done
          echo "Valid input"
        env:
          REPO_LIST: ${{ github.event.inputs.feedstocks }}

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Create Conda environment
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: agg
          cache-downloads: true
          cache-env: true
          extra-specs: |
            python=3.9

      - name: Get dependencies
        id: deps
        run: |          
          python tools/crawl_deptree.py -f ${{ github.event.inputs.feedstocks }} > output.log
          feedstocks+=$(tail -n 1 output.log)
          echo "feedstocks=$feedstocks" >> $GITHUB_OUTPUT
        env:
          REPO_LIST: ${{ github.event.inputs.feedstocks }}

      - name: Prune repos that already exists
        id: prune
        run: |
          # Check gh is authenticated
          gh auth status >/dev/null || exit 1
          addlist=""
          for NEW_FEEDSTOCK in ${REPO_LIST//,/ }; do
            echo "Checking if anaconda-community/${NEW_FEEDSTOCK} already exists"
            # Check if the repo has already been forked
            gh repo view anaconda-community/${NEW_FEEDSTOCK} > /dev/null && echo "anaconda-community/${NEW_FEEDSTOCK} already exists" || addlist+="${NEW_FEEDSTOCK},"
          done
          echo "feedstocks=$addlist" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_LIST: ${{ steps.deps.outputs.feedstocks }}

      - name: Fork repo
        if: ${{ steps.prune.outputs.feedstocks != '' }}
        run: |
          for repo in ${REPO_LIST//,/ }; do
            gh repo fork https://github.com/conda-forge/$repo --org anaconda-community --clone=false --default-branch-only
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_LIST: ${{ steps.prune.outputs.feedstocks }}

      - name: View fork
        if: ${{ steps.prune.outputs.feedstocks != '' }}
        run: |
          for repo in ${REPO_LIST//,/ }; do
            gh repo view anaconda-community/$repo > /dev/null
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_LIST: ${{ steps.prune.outputs.feedstocks }}

      - name: Update manifest
        id: manifest
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          branch=$(date +addfeedstocks%Y%m%d%H%M%S)
          git checkout -b $branch
          for repo in ${REPO_LIST//,/ }; do
            until git ls-remote https://github.com/anaconda-community/${repo}.git &> /dev/null
            do
              echo "Waiting on repo..."
              sleep 1
            done
            hash=$(git ls-remote https://github.com/anaconda-community/${repo}.git | head -n1 | awk '{print $1;}')
            abs aggregate add --branch main --commit ${hash} ${repo}
          done
          yq --yaml-output --in-place . manifest.yaml
          git add manifest.yaml
          git commit -m "add ${{ github.event.inputs.feedstocks }}" && git push --set-upstream origin $branch && echo "createpr=true" >> $GITHUB_OUTPUT || echo "createpr=false" >> $GITHUB_OUTPUT
        env:
          REPO_LIST: ${{ steps.deps.outputs.feedstocks  }}

      - name: Open PR
        if: ${{ steps.manifest.outputs.createpr == 'true' }}
        run: gh pr create --fill --label "manifest-add"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
