name: "Add repo"
on:
  workflow_dispatch:
    inputs:
      repoUrl:
        description: 'URL for feedstock that will be added. To add multiple at once separate by a space'
        required: true
        type: string
permissions: write-all

jobs:
  add-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        run: |
          for repo in $REPO_LIST; do 
            echo "Checking input $repo"
            if [[ ! $repo =~ ^http.*conda-forge/[A-Za-z0-9_.-]+-feedstock$ ]]; then
                echo "Invalid input $repo. Please enter repos of the form https://github.com/conda-forge/<library>-feedstock"
                exit 1
            fi
          done
          echo "Valid input"
        env:
          REPO_LIST: ${{ github.event.inputs.repoUrl }}

      - name: Check if repo already exists
        run: |
          # Check gh is authenticated
          gh auth status >/dev/null || exit 1
          for repo in $REPO_LIST; do
            NEW_FEEDSTOCK=$(echo $repo | sed -r 's#^http.*conda-forge/([A-Za-z0-9_.-]+-feedstock)$#\1#')
            echo "Checking if anaconda-community/${NEW_FEEDSTOCK} already exists"
            # Check if the repo has already been forked
            gh repo view anaconda-community/${NEW_FEEDSTOCK} > /dev/null && echo "anaconda-community/${NEW_FEEDSTOCK} already exists" && exit 1 || echo "anaconda-community/${NEW_FEEDSTOCK} does not exist"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_LIST: ${{ github.event.inputs.repoUrl }}

      - name: Fork repo
        run: |
          for repo in $REPO_LIST; do
            gh repo fork $repo --org anaconda-community --clone=false --default-branch-only
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_LIST: ${{ github.event.inputs.repoUrl }}

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/agg
          key: conda-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auth-activate-base: false
          activate-environment: agg
          channels: distro-tooling,conda-forge
          python-version: 3.9
          mamba-version: "*"
          environment-file: environment.yml

      - name: Add submodule
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          branch=$(date +addfeedstocks%Y%m%d%H%M%S)
          git checkout -b $branch
          for repo in $REPO_LIST; do
            feedstock=${repo:31}
            hash=$(git ls-remote https://github.com/anaconda-community/${feedstock}.git | head -n1 | awk '{print $1;}')
            abs aggregate add --branch main --commit ${hash} ${feedstock}
          done
          yq --yaml-output --in-place . manifest.yaml
          git add manifest.yaml
          git commit -m "add ${REPO_LIST}"
          git push --set-upstream origin $branch
        env:
          REPO_LIST: ${{ github.event.inputs.repoUrl }}

      - name: Open PR
        run: gh pr create --fill --label "manifest-add"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
