name: "Add repo"
on:
  workflow_dispatch:
    inputs:
      repoUrl:
        description: 'URL for feedstock that will be added'
        required: true
        type: string
permissions: write-all

jobs:
  add-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Fork repo
        run: gh repo fork ${{ github.event.inputs.repoUrl }} --org anaconda-community --clone=false --default-branch-only
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/agg
          key: conda-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auth-activate-base: false
          activate-environment: agg
          channels: distro-tooling,conda-forge
          python-version: 3.9
          mamba-version: "*"
          environment-file: environment.yml

      - name: Add submodule
        run: |
          feedstock=${REPO:31}
          hash=$(git ls-remote https://github.com/anaconda-community/${feedstock}.git | head -n1 | awk '{print $1;}')
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $feedstock
          abs aggregate add --branch main --commit ${hash} ${feedstock}
          git add manifest.yaml
          git commit -m "add ${feedstock}"
          git push --set-upstream origin $feedstock
        env:
          REPO: ${{ github.event.inputs.repoUrl }}

      - name: Open PR
        run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
