name: "Build feedstock"

on:
  workflow_dispatch:
    inputs:
      feedstocks:
        description: 'Feedstocks to build in order, comma separated'
        required: true
        type: string
      arch:
        description: 'Architecture to target'
        default: "linux-64"
        required: true
        type: choice
        options:
          - linux-64
      container_runtime:
        description: 'The container runtime to use'
        default: none
        type: choice
        options:
          - docker
          - podman
          - none
      branch:
        description: 'Branch from anaconda-community/aggregate youd like to build from'
        default: main
        required: true
      action_runner:
        description: "The GitHub runner to use, only change when eks does not work"
        default: "self-hosted-eks"
        required: true
        type: choice
        options:
          - "self-hosted-eks"
          - "ubuntu-latest"

permissions: write-all

env:
  ACTION: "Build on Prod-Community Manual Start"


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Start build
        run: gh -R anaconda-distribution/rocket-platform workflow run "$ACTION" -f feedstock=${{ inputs.feedstocks }} -f arch=${{ inputs.arch }} -f action_runner=${{ inputs.action_runner }} -f container_runtime=${{ inputs.container_runtime }} -f branch=${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}