name: "Build feedstocks"

on:
  workflow_call:
    inputs:
      feedstock:
        description: 'Feedstock to build'
        required: true
        type: string
      arch:
        description: 'Architecture to target'
        default: "linux-64"
        type: string
      container_runtime:
        description: 'The container runtime to use'
        default: "docker"
        type: string
      branch:
        description: 'Branch from anaconda-community/aggregate youd like to build from'
        default: main
        type: string
      action_runner:
        description: "The GitHub runner to use, only change when eks does not work"
        default: "self-hosted-eks"
        type: string
      manifest:
        description: "Flag to run build for entire manifest"
        default: "False"
        type: string
      add_deps:
        description: "Flag to add dependencies"
        default: "True"
        type: string
    secrets:
      GH_TOKEN:
        description: 'Github Token'
        required: true

permissions: write-all

env:
  ACTION: "Build on Prod-Community Manual Start"


jobs:
  build-order:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    outputs:
      feedstocks: ${{ steps.build-order.outputs.feedstocks }}
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Create Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: agg
          cache-downloads: true
          cache-env: true
          extra-specs: |
            python=3.9

      - name: Get build order
        id: build-order
        run: |
          if [[ ${{ inputs.add_deps }} == "True" ]]
          then
            python tools/find_deps.py -f ${{ inputs.feedstock }} -m ${{ inputs.manifest }} > output.log
            feedstocks=$(tail -n 1 output.log)
          else
            feedstocks=${{ inputs.feedstock }}
          fi
          echo "feedstocks=$feedstocks" >> $GITHUB_OUTPUT

  build:
    needs: build-order
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Start build
        run: gh -R anaconda-distribution/rocket-platform workflow run "$ACTION" -f feedstock=${{ needs.build-order.outputs.feedstocks }} -f arch=${{ inputs.arch }} -f action_runner=${{ inputs.action_runner }} -f container_runtime=${{ inputs.container_runtime }} -f branch=${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}