name: "Build feedstocks"

on:
  workflow_call:
    inputs:
      feedstock:
        description: 'Feedstock to build'
        required: true
        type: string
      arch:
        description: 'Architecture to target'
        default: "linux-64"
        type: string
      container_runtime:
        description: 'The container runtime to use'
        default: none
        type: string
      branch:
        description: 'Branch from anaconda-community/aggregate youd like to build from'
        default: main
        type: string
      action_runner:
        description: "The GitHub runner to use, only change when eks does not work"
        default: "self-hosted-eks"
        type: string
    secrets:
      GH_TOKEN:
        description: 'Github Token'
        required: true
        type: string

permissions: write-all

env:
  ACTION: "Build on Prod-Community Manual Start"


jobs:
  build-order:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    outputs:
      feedstocks: ${{ steps.build-order.outputs.feedstocks }}
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/agg
          key: conda-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auth-activate-base: false
          activate-environment: agg
          channels: distro-tooling,conda-forge
          python-version: 3.9
          mamba-version: "*"
          environment-file: environment.yml

      - name: Get build order
        id: build-order
        run: |
          python tools/find_deps.py -f ${{ inputs.feedstock }} > output.log
          feedstocks=$(tail -n 1 output.log)
          echo "feedstocks=$feedstocks" >> $GITHUB_OUTPUT

  build:
    needs: build-order
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Start build
        run: gh -R anaconda-distribution/rocket-platform workflow run "$ACTION" -f feedstock=${{ needs.build-order.outputs.feedstocks }} -f arch=${{ inputs.arch }} -f action_runner=${{ inputs.action_runner }} -f container_runtime=${{ inputs.container_runtime }} -f branch=${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}