#  Test flow:
#
#  1. Updates recipe in anaconda-community/community-integration-test-feedstock to increment build number
#  2. Updates manifest on a branch to the latest community-integration-test-feedstock
#       commit and calls build workflow with branch information
#  3. Poll repodata.json for the package with the build number
#  4. Conda install the package
#  5. Send results to datadog
name: Integration Test

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch: {}

jobs:
  integration-test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Community-Integration-Test-Feedstock Repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
        with:
          repository: anaconda-community/community-integration-test-feedstock
          token: ${{ secrets.GH_TOKEN }}

      - name: Create Conda environment with abs
        uses: mamba-org/setup-micromamba@5d5dbebd87f7b9358c403c7a66651fa92b310105 #v1.4.1
        with:
          environment-name: integration-test
          cache-downloads: true
          log-level: warning
          condarc: | 
            channels:
              - conda-forge
              - distro-tooling
          create-args: >-
            abs-cli
            yq

      - name: Get build number
        id: build_number
        run: |          
          value=$(yq '.build.number' recipe/meta.yaml)
          ((value++))
          echo "result=$value" >> $GITHUB_OUTPUT          

      - name: Update recipe
        id: recipe
        run: |          
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"          
          yq -y -i '.build.number = ${{ steps.build_number.outputs.result }}' recipe/meta.yaml
          git add recipe/meta.yaml
          git commit -m "update build number" && git push --set-upstream origin main --force             

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Update manifest
        id: manifest
        run: |
          hash=$(git ls-remote https://github.com/anaconda-community/community-integration-test-feedstock.git | head -n1 | awk '{print $1;}')
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b community-integration-test-branch          
          abs aggregate add --branch main --commit ${hash} community-integration-test-feedstock
          yq --yaml-output --in-place . manifest.yaml
          git add manifest.yaml
          git commit -m "update community-integration-test-feedstock" && git push --set-upstream origin community-integration-test-branch --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: |
          gh secret set GH_TOKEN --body "$GITHUB_TOKEN"
          gh -R anaconda-community/aggregate workflow run "Manual build feedstock" \
            -f feedstock=community-integration-test-feedstock \
            -f arch=linux-64 \
            -f branch=community-integration-test-branch \
            -f add_deps=false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Poll Repodata.json
        id: poll_repodata
        run: |
          timeout=600  # 10 minutes
          start_time=$(date +%s)
          while true; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))

            # check repodata.json
            package_name=community-integration-test-0.4.6-py_${{ steps.build_number.outputs.result }}.tar.bz2          
            response=$(curl -s https://repo.anaconda.cloud/repo/t/$ANACONDA_BUSINESS_TOKEN/community_testing/noarch/repodata.json)            
            repo_package=$(echo "$response" | jq -r ".packages.\"${package_name}\"")
          
            if [[ "$repo_package" != "null" ]]; then
              echo "Found package in repodata.json: $repo_package"   
              echo "timeout_reached=0" >> $GITHUB_OUTPUT
              echo "repodata_package=$package_name" >> $GITHUB_OUTPUT
              break
            fi

            # Check if timeout reached
            if [[ $elapsed_time -gt $timeout ]]; then
              echo "Timeout reached, did not detect package: ${package_name} within 10 minutes."
              echo "timeout_reached=1" >> $GITHUB_OUTPUT
              echo "repodata_package=$package_name" >> $GITHUB_OUTPUT
              break
            fi

            sleep 60  # Wait for 1 minute before polling again
          done
        env:
          ANACONDA_BUSINESS_TOKEN: ${{ secrets.ANACONDA_BUSINESS_TOKEN }}

      - name: Install package
        id: install
        if: ${{ steps.poll_repodata.outputs.timeout_reached }} != "1"
        run: |          
          conda install -y community-integration-test --channel https://repo.anaconda.cloud/repo/t/$ANACONDA_BUSINESS_TOKEN/us-conversion/community_test
          
          if conda list | grep community-integration-test; then
            echo "Found installed pacakge"
            echo "test_result=Success" >> $GITHUB_OUTPUT            
          else
            echo "Failed to install"
            echo "test_result=Error" >> $GITHUB_OUTPUT
          fi
        env:
          ANACONDA_BUSINESS_TOKEN: ${{ secrets.ANACONDA_BUSINESS_TOKEN }}

      - name: Send Integration Test Event
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          events: |
            - title: "Community Repo Integration Test ${{ steps.install.outputs.test_result }}"
              text: "Test ${{ steps.install.outputs.test_result }}"
              alert_type: "${{ steps.install.outputs.test_result }}"
              host: ${{ github.repository_owner }}
              tags:
                - "@github.org:anaconda-community"                
                - "package-name:${{ steps.poll_repodata.outputs.repodata_package }}"