name: "Manual build feedstock"

on:
  workflow_dispatch:
    inputs:
      feedstock:
        description: 'Feedstock to build'
        required: true
        type: string
      arch:
        description: 'Architecture to target'
        default: "linux-64"
        required: true
        type: choice
        options:
          - linux-64
      container_runtime:
        description: 'The container runtime to use'
        default: "docker"
        type: choice
        options:
          - docker
          - podman
          - none
      branch:
        description: 'Branch from anaconda-community/aggregate youd like to build from'
        default: main
        required: true
      action_runner:
        description: "The GitHub runner to use, only change when eks does not work"
        default: "self-hosted-eks"
        required: true
        type: choice
        options:
          - "self-hosted-eks"
          - "ubuntu-latest"
      manifest:
        description: "Flag to build entire manifest"
        default: false
        required: true
        type: boolean
      add_deps:
        description: "Flag to add dependencies"
        default: false
        type: boolean
        required: true
      skip_published:
        description: "Flag to skip published"
        default: false
        type: boolean
        required: true

permissions: write-all

jobs:
  build:
    uses: anaconda-community/aggregate/.github/workflows/build-feedstock.yml@main
    with:
      feedstock: ${{ inputs.feedstock }}
      arch: ${{ inputs.arch }}
      container_runtime: ${{ inputs.container_runtime }}
      branch: ${{ inputs.branch }}
      action_runner: ${{ inputs.action_runner }}
      manifest: ${{ inputs.manifest }}
      add_deps: ${{ inputs.add_deps }}
      skip_published: ${{ inputs.skip_published }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}