name: "Remove repo"
on:
  workflow_dispatch:
    inputs:
      feedstock:
        description: 'Name of feedstock that will be removed'
        required: true
        type: string
permissions: write-all

jobs:
  remove-repo:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
#
#      - name: Remove from manifest
#        run: |
#          echo "TBD"
#
#      - name: Open PR
#        run: gh pr create --fill
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete repo
        run: gh repo delete https://github.com/anaconda-community/${{ github.event.inputs.feedstock }} --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}