name: "Remove repo"
on:
  workflow_dispatch:
    inputs:
      feedstocks:
        description: 'Name of feedstock that will be removed, to remove multiple separate by comma'
        required: true
        type: string
permissions: write-all

jobs:
  remove-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Create Conda environment
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: agg
          cache-downloads: true

      - name: Remove from manifest
        run: |
          for repo in ${REPO_LIST//,/ }; do
            yq -i -y 'del(.feedstocks."'"$repo"'")' manifest.yaml
          done
        env:
          REPO_LIST: ${{ github.event.inputs.feedstocks }}

      - name: Commit change
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          branch=$(date +removefeedstocks%Y%m%d%H%M%S)
          git checkout -b $branch
          git add manifest.yaml
          git commit -m "remove ${{ github.event.inputs.feedstocks }}" && git push --set-upstream origin $branch && gh pr create --fill --label "manifest-remove"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete repo
        run: |
          for repo in ${REPO_LIST//,/ }; do
            gh repo delete https://github.com/anaconda-community/$repo --yes
          done
        env:
          REPO_LIST: ${{ github.event.inputs.feedstocks }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Format output
        id: formatted
        run: |     
          formatted_feedstocks=$(echo $FEEDSTOCKS | yq 'split(",")' -c)
          echo "feedstocks=$formatted_feedstocks" >> $GITHUB_OUTPUT
        env:
          FEEDSTOCKS: ${{ github.event.inputs.feedstocks }}

    outputs:
      feedstocks: ${{ steps.formatted.outputs.feedstocks }}

  send-dd-remove-events:
    needs: remove-repo
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    if: ${{ needs.remove-repo.outputs.feedstocks != '' }}
    strategy:
      matrix:
        feedstock: ${{ fromJson(needs.remove-repo.outputs.feedstocks) }}
    steps:
      - name: Send Remove Feedstock Event
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          events: |
            - title: "Removed feedstock ${{ matrix.feedstock }}"
              aggregation_key: "community-repo/feedstock-removed"
              text: "Feedstock ${{ matrix.feedstock }} was removed."
              alert_type: "info"
              host: ${{ github.repository_owner }}
              tags:
                - "@github.org:anaconda-community"
                - "service:community-repo"