name: "Remove repo"
on:
  workflow_dispatch:
    inputs:
      feedstocks:
        description: 'Name of feedstock that will be removed, to remove multiple separate by comma'
        required: true
        type: string
permissions: write-all

jobs:
  remove-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Create Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: agg
          cache-downloads: true
          cache-env: true
          extra-specs: |
            python=3.9

      - name: Remove from manifest
        run: |
          for repo in ${REPO_LIST//,/ }; do
            yq -i -y 'del(.feedstocks."'"$repo"'")' manifest.yaml
          done
        env:
          REPO_LIST: ${{ github.event.inputs.feedstocks }}

      - name: Commit change
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          branch=$(date +removefeedstocks%Y%m%d%H%M%S)
          git checkout -b $branch
          git add manifest.yaml
          git commit -m "remove ${{ github.event.inputs.feedstocks }}" && git push --set-upstream origin $branch && gh pr create --fill --label "manifest-remove"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete repo
        run: |
          for repo in ${REPO_LIST//,/ }; do
            gh repo delete https://github.com/anaconda-community/$repo --yes
          done
        env:
          REPO_LIST: ${{ github.event.inputs.feedstocks }}