name: "Sync pinnings"
# Don't want to run daily yet, but might be best option in future
#on:
#  schedule:
#    - cron: 0 0 * * *
on: workflow_dispatch

jobs:
  sync-pinnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Checkout AnacondaRecipes
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
        with:
          repository: AnacondaRecipes/aggregate
          path: aggregate

      - name: Check-in change
        run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git checkout -b pinnings
            mv aggregate/conda_build_config.yaml conda_build_config.yaml
            cat conda_build_config_additions.yaml >> conda_build_config.yaml            
            git add conda_build_config.yaml
            git commit -m "Update conda_build_config.yaml" && git push --set-upstream origin pinnings && gh pr create --fill --label pinnings || echo "No changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
