name: "Update repo"
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo name of feedstock to update'
        required: true
        type: string
permissions: write-all

jobs:
  update-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        run: gh repo sync anaconda-community/${{ github.event.inputs.repo }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/agg
          key: conda-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auth-activate-base: false
          activate-environment: agg
          channels: distro-tooling,conda-forge
          python-version: 3.9
          mamba-version: "*"
          environment-file: environment.yml

      - name: Update manifest
        id: manifest
        run: |
          hash=$(git ls-remote https://github.com/anaconda-community/${REPO}.git | head -n1 | awk '{print $1;}')
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $feedstock
          abs aggregate add --branch main --commit ${hash} ${REPO}
          git add manifest.yaml
          git commit -m "update ${feedstock}" && git push --set-upstream origin $feedstock && echo "createpr=true" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.event.inputs.repo }}

      - name: Open PR
        if: ${{ steps.manifest.outputs.createpr == 'true' }}
        run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
