name: "Update repo"
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo name of feedstock to update'
        required: true
        type: string
permissions: write-all

jobs:
  update-repo:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        run: gh repo sync anaconda-community/${{ github.event.inputs.repo }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Create Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: agg
          cache-downloads: true
          cache-env: true
          extra-specs: |
            python=3.9

      - name: Update manifest
        id: manifest
        run: |
          hash=$(git ls-remote https://github.com/anaconda-community/${REPO}.git | head -n1 | awk '{print $1;}')
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $REPO
          abs aggregate add --branch main --commit ${hash} ${REPO}
          yq --yaml-output --in-place . manifest.yaml
          git add manifest.yaml
          git commit -m "update ${REPO}" && git push --set-upstream origin $REPO && echo "createpr=true" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.event.inputs.repo }}

      - name: Open PR
        if: ${{ steps.manifest.outputs.createpr == 'true' }}
        run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
